<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DataMonitor.Core\DataMonitor.Core.csproj" />
    <ProjectReference Include="..\DataMonitor.Infrastructure\DataMonitor.Infrastructure.csproj" />
    <ProjectReference Include="..\DataMonitor.Database\DataMonitor.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="Wpf.Ui" Version="3.4.2.7" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>DataMonitor</Product>
    <ApplicationIcon>Assets\DataMonitor.ico</ApplicationIcon>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataMonitor.MonitorService\DataMonitor.MonitorService.csproj" />
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
    <Resource Include="Assets\DataMonitor.ico" />
  </ItemGroup>
</Project>

